package save

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// The save-transfer wire format, identical to the web game's transfer.ts: a
// base64-encoded JSON envelope of terminal (won/lost) day records. `btoa` over
// ASCII JSON is exactly base64.StdEncoding, so strings round-trip with
// connections.audio's Settings → Copy backup / Import.

const (
	// FormatVersion mirrors transfer.ts FORMAT_VERSION.
	FormatVersion = 1
	// AppTag gates imports to backups from this game.
	AppTag = "audio-connections"
)

// TransferGuess is the wire guess shape — themes + correctness, no track ids
// (so a backup never leaks which tracks were picked on wrong guesses).
type TransferGuess struct {
	Themes  []int `json:"themes"`
	Correct bool  `json:"correct"`
}

// PerDayRecord is one terminal day on the wire.
type PerDayRecord struct {
	Day          int             `json:"day"`
	Outcome      string          `json:"outcome"` // "won" | "lost"
	GuessHistory []TransferGuess `json:"guessHistory,omitempty"`
}

type envelope struct {
	FormatVersion int            `json:"formatVersion"`
	ExportedAt    string         `json:"exportedAt"`
	App           string         `json:"app"`
	Days          []PerDayRecord `json:"days"`
}

// EncodeBackup serializes the terminal days among recs into a transfer string.
// In-progress records are skipped (the wire format is terminal-only).
func EncodeBackup(recs []Record, exportedAt string) string {
	days := make([]PerDayRecord, 0, len(recs))
	for _, r := range recs {
		if !r.GameOver {
			continue
		}
		pd := PerDayRecord{Day: r.Day, Outcome: outcome(r)}
		for _, g := range r.GuessHistory {
			pd.GuessHistory = append(pd.GuessHistory, TransferGuess{Themes: g.Themes, Correct: g.Correct})
		}
		days = append(days, pd)
	}
	sort.Slice(days, func(i, j int) bool { return days[i].Day < days[j].Day })

	env := envelope{FormatVersion: FormatVersion, ExportedAt: exportedAt, App: AppTag, Days: days}
	raw, _ := json.Marshal(env)
	return base64.StdEncoding.EncodeToString(raw)
}

func outcome(r Record) string {
	if r.Won() {
		return "won"
	}
	return "lost"
}

// DecodeBackup parses a transfer string into its day records, validating the
// envelope the same way transfer.ts decodeBackup does.
func DecodeBackup(b64 string) ([]PerDayRecord, error) {
	trimmed := strings.TrimSpace(b64)
	if trimmed == "" {
		return nil, fmt.Errorf("empty input")
	}
	raw, err := base64.StdEncoding.DecodeString(trimmed)
	if err != nil {
		// Tolerate a string that lost its `=` padding in transit.
		raw, err = base64.RawStdEncoding.DecodeString(trimmed)
		if err != nil {
			return nil, fmt.Errorf("doesn't look like a backup string")
		}
	}
	var env envelope
	if err := json.Unmarshal(raw, &env); err != nil {
		return nil, fmt.Errorf("backup is corrupted (not valid JSON)")
	}
	if env.App != AppTag {
		return nil, fmt.Errorf("this backup was generated by a different app")
	}
	if env.FormatVersion > FormatVersion {
		return nil, fmt.Errorf("backup is from a newer build — update ac-term to import it")
	}
	for i, d := range env.Days {
		if d.Outcome != "won" && d.Outcome != "lost" {
			return nil, fmt.Errorf("day record #%d is malformed", i+1)
		}
	}
	return env.Days, nil
}

// Materialize turns a wire day record into a full persisted Record for the
// given puzzle id and track count, mirroring the web game's materializeRecord:
// a terminal save with all themes solved, mistakes inferred from the guess
// history (or the outcome when history is absent), and a positional trackOrder.
func Materialize(td PerDayRecord, id string, trackCount int) Record {
	mistakes := 0
	if td.GuessHistory != nil {
		for _, g := range td.GuessHistory {
			if !g.Correct {
				mistakes++
			}
		}
	} else if td.Outcome != "won" {
		mistakes = MaxMistakes
	}

	guesses := make([]Guess, 0, len(td.GuessHistory))
	for _, g := range td.GuessHistory {
		guesses = append(guesses, Guess{Themes: g.Themes, Correct: g.Correct, IDs: []int{}})
	}

	order := make([]int, trackCount)
	for i := range order {
		order[i] = i
	}

	return Record{
		V:               Version,
		ID:              id,
		Day:             td.Day,
		Selected:        []int{},
		SolvedThemes:    []int{0, 1, 2, 3},
		Notes:           []Note{},
		Mistakes:        mistakes,
		GuessHistory:    guesses,
		GameOver:        true,
		TrackOrder:      order,
		GuessSignatures: []string{},
	}
}

// Clear wipes all saved progress (used by import --replace).
func Clear() error { return writeAll(map[string]Record{}) }
